@startuml Basic Sample

title Передача актуальных ставок по депозитам в кол-центр

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(credits_manager, "Менеджер\nотдела кредитов")

System_Ext(call_center, "Система кол-центра", "Управляет звонками клиентам")
System_Ext(outsource_call_center, "Система партнерского кол-центра", "Управляет звонками клиентам")

System_Boundary(internet_bank, "Интернет банк") {
    Container(ib_admin, "Панель администратора", "C#, ASP.NET MVC 4.5", "Веб-приложение")
    Container(deposits, "Сервис депозитов", "C#, ASP.NET MVC 4.5", "Управляет депозитами клиентов")
    ContainerDb(deposits_data, "База данных депозитов", "MS SQL", "Заявки и депозиты клиентов, актуальные ставки, персональные предложения")
    ContainerDb(deposits_files, "Хранилище файлов", "NAS", "Файлы с актуальными ставками по депозитам")
}

Rel_D(credits_manager, ib_admin, "Актуализирует ставки", "HTTPS")
Rel_D(ib_admin, deposits, "Актуализирует ставки", "REST")
Rel_D(deposits, deposits_data, "Чтение/Запись", "SQL")
Rel_D(deposits, deposits_files, "Чтение/Запись", "NFS")

Rel_U(deposits, call_center, "Передает файл с актуальными ставками", "SFTP")
Rel_U(deposits, outsource_call_center, "Передает файл с актуальными ставками", "SFTP")

@enduml